version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres # should be from env also
      POSTGRES_PASSWORD: postgres # should be from env also
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/products_db"
    ports:
      - "8000:8000"
    # Default command: start the API.
    # To run migrations instead, override this command.
    command: ["python", "src/__main__.py", "runapi"]

volumes:
  postgres_data:
